# Nom du workflow
name: first workflow

# Trigger
on: [workflow_dispatch]

# Actions à réaliser lors du trigger
jobs:
  # Nom du job
  first-job:
    name: my first job
    # Type de runner
    runs-on: ubuntu-latest
    # Etapes à réaliser
    steps:
      # Nom de l'action
      - name: say hello
        # Action à réaliser
        run: echo "Hello, world!"
      # Nom de l'action
      - name: say bye
        # Action à réaliser
        run: echo "Bye, world!"

    # second job
  second-job:
    name: my second job
    runs-on: ubuntu-latest
    steps:
      - name: my step
        run: echo "I'm the second job!"
